<?php $ticket = $this->ticketData; ?>

<h1>Ticket Information</h1>

<p>
    <?php if ($ticket->getSolved()) : ?>
        <span class="label label-success">Solved</span>
    <?php endif; ?>

    <?php if (! $ticket->getActive()) : ?>
        <span class="label label-danger">Closed</span>
    <?php endif; ?>
</p>

<table class="table">
    <tbody>
    <tr>
        <td><strong>Subject</strong></td>
        <td>
            <?php echo $ticket->getSubject(); ?>
        </td>
    </tr>
    <tr>
        <td><strong>Description</strong></td>
        <td><?php echo nl2br($ticket->getDescription()); ?></td>
    </tr>
    <tr>
        <td><strong>Importance</strong></td>
        <td><?php echo $ticket->getImportance(); ?></td>
    </tr>
    <tr>
        <td colspan="2">
            <?php if (! $ticket->getSolved()) : ?>
                <a href="<?php echo $this->url('ticket/solve', [], null, true); ?>" class="btn btn-success">Mark as solved</a>
            <?php endif; ?>

            <?php if ($ticket->getActive()) : ?>
                <a href="<?php echo $this->url('ticket/close', [], null, true); ?>" class="btn btn-danger">Close Ticket</a>
            <?php else: ?>
                <a href="<?php echo $this->url('ticket/reopen', [], null, true); ?>" class="btn btn-success">Reopen Ticket</a>
            <?php endif; ?>
        </td>
    </tr>
    </tbody>
</table>


<?php foreach ($comments as $comment): ?>
    <blockquote><?php echo $comment->getComment(); ?></blockquote>
    <hr/>
<?php endforeach; ?>

<div class="container">
    <div class="row">
        <strong>Comments:</strong>
        <?php
        $form = $this->commentForm;
        $form->setAttribute('action', $this->url('ticket/comment', [], null, true));

        echo $this->form()->openTag($form);
        ?>

        <div><?php echo $this->formRow($form->get('comment')); ?></div>
        <div><?php echo $this->formSubmit($form->get('submit')); ?></div>

        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>
